project:
  name: trail_agent
  version: 0.1.0
  description: Blog-writing agent using YouTube video research
  entrypoint: crew.py
  python_version: "3.10"
  dependencies:
    - crewai
    - crewai-tools
    - langchain
    - python-dotenv

tasks:
  - id: research_task
    description: "Identify the video {topic}. Get detailed information about the video from the YouTube channel."
    expected_output: "A comprehensive 3-paragraph long report based on the {topic} of video content."
    tools:
      - youtube_channel_search_tool
    agent: blog_researcher

  - id: write_task
    description: "Get the info from the YouTube channel on the topic {topic}."
    expected_output: "Summarize the info from the YouTube channel video on the topic {topic} and create the content for the blog."
    tools:
      - youtube_channel_search_tool
    agent: blog_writer
    async_execution: false
    output_file: new-blog-md
